### ISSUE TITLE
Tagged 1.8.4 release shows 1.8.3 as version

### ISSUE THREAD

**Issue by jadeallenx** [yitsushi/totp-cli#100]

**Comment by yitsushi** [comment]
pfff... I should prioritise https://github.com/yitsushi/totp-cli/issues/38, always forget to bump that in the file :( sorry

**Comment by yitsushi** [comment]
https://github.com/yitsushi/totp-cli/releases/tag/v1.8.5

**Comment by yitsushi** [comment]
```
❯ totp-cli --version
totp-cli version v1.8.5
```

Now it reports back the correct version. I'll try to resolved #38 asap so it never happens again.
