### ISSUE TITLE
Allow syncing of encrypted codes

### ISSUE THREAD

**Issue by nathfavour** [yitsushi/totp-cli#109]
Just like how Joplin works, I believe this qrcode package can be made to sync across devices (both mobile and desktop), thus creating a free and open source Authenticator app

..or is this too ambitious, lol

**Comment by yitsushi** [comment]
This is a cli tool to store tokens and generate OTPs. Nothing more.

You can sync already if you want, you can set the `TOTP_CLI_CREDENTIAL_FILE` env variable to a location that's synced with Syncthing or anything.

Free and open source there are other authenticator apps out there.
