### ISSUE TITLE
illegal base32 at byte 24

### ISSUE THREAD

**Issue by josephspurrier** [yitsushi/totp-cli#16]
I received this error when decoding my 26 character secret.

You should probably update your code to decode the secret using this: https://github.com/gokyle/twofactor/issues/10#issuecomment-381966785

**Comment by yitsushi** [comment]
I think it's a different problem, I met this problem before when I copied the given secret and later I discovered sometimes it's base64 encoded as an extra layer.

if try the token from the linked issue `a6mryljlbufszudtjdt42nh5by` it does not fail on illegal byte and if I add the `NoPadding` option in there, then I get an error:

```
illegal base32 data at input byte 40
```

However it seems it does not yield a valid 6digit code. :(

**Comment by yitsushi** [comment]
nvm, my bad... I tried with the right token, but instead of decoding it i decoded again so it was valid. :(

**Comment by yitsushi** [comment]
@josephspurrier : `totp-cli update` will update your binary with the shiny new `1.0.5` (or `go get`/`go install` of course).

Thanks for the report and the link to that comment ;)

**Comment by josephspurrier** [comment]
Great, glad I could assist!
