### ISSUE TITLE
Can not generate OTP when using "." in account name

### ISSUE THREAD

**Issue by sunpoet** [yitsushi/totp-cli#18]
% totp-cli add-token test foo@bar.com
Token:
Password: ***

% totp-cli list test
Password: ***
test.foo@bar.com

% totp-cli generate test.foo@bar.com
Password: ***
Account not found

**Comment by sunpoet** [comment]
The failure is actually caused by "." in account name, not "@".

Would it be simpler to have consistent usage?
"namespace account" is used for add-token. 
"namespace.account" is used for other commands.

I guess "." is acceptable if the former format is used among all commands.

**Comment by yitsushi** [comment]
I was thinking about removing the `.` separator and simply use them as a different parameter instead, but because I never tried to use `.` in account names I never felt the urge to do it.

**Comment by yitsushi** [comment]
@sunpoet : v1.1.1 is available with these changes. You can't use the `update` command for it because the update was updated to use `tar.gz` instead of raw executable (without compression).

Nothing changed about stored data and how it reads them only the command parsing.

**Comment by sunpoet** [comment]
@yitsushi Thanks, it works fine!
I use email address as account which contains dots.
