### ISSUE TITLE
Premade releases don't run on glibc based systems.

### ISSUE THREAD

**Issue by NamedKitten** [yitsushi/totp-cli#21]
Hey it seems the binarys you provide are built on a musl based system, could you try setting CGO_ENABLED=0 so that it doesn't link to them? It is currently dynamically linked and using the musl libc loader which causes the error `bash: ./totp-cli: No such file or directory` and ldd result `libc.musl-x86_64.so.1 => not found`

**Comment by yitsushi** [comment]
I think #23 will fix this problem, later on I'll create a new release (not during my working hours because I want to follow what's happening and manually test the product of the GitHub action).

**Comment by yitsushi** [comment]
(and sry GitHub did not notify me about your issues/PR

ok actually it did but it just lost in the 100+ notification / day from corporate private repos)

**Comment by NamedKitten** [comment]
That's fine! thanks for checking back :3
do you have xmpp, telegram,discord, irc, etc?

**Comment by yitsushi** [comment]
Released, please verify it for me. On my side it's working, but I don't want to close it without a proof.

https://github.com/yitsushi/totp-cli/releases/tag/v1.1.5

(yes, efertone on irc and discord as well, and I use a ton of messengers, Keybase even connected with my github profile)

**Comment by yitsushi** [comment]
Verified on Manjaro 18.1.0. It works.
