### ISSUE TITLE
Re-add windows releases?

### ISSUE THREAD

**Issue by sharunkumar** [yitsushi/totp-cli#31]
Just discovered this repo and looking for windows releases

currently I am using v1.1.3 which was the last windows version released

any specific reason as to why it was removed?

**Comment by yitsushi** [comment]
To be honest, I have no idea why I dropped it. Sadly I was too lazy to document what was broken.

At least not in this PR or the commit message of its only commit: https://github.com/yitsushi/totp-cli/pull/24

I'll look into it on this weekend.

**Comment by sharunkumar** [comment]
In the mean time could you tell me where the data for this app is stored in this version? in case I need to move it to another system

**Comment by yitsushi** [comment]
@sharunkumar: It's under `$HOME\.config\totp-cli\` and `$HOME` is usually `C:\Users\YourUsername>`

**Comment by yitsushi** [comment]
Meanwhile, locally I was able to build a windows binary.

**Comment by yitsushi** [comment]
@sharunkumar: Can you check if it's working for you (v1.1.1)?

```
PS C:\> .\totp-cli.exe list
Password: ***
test (Number of accounts: 1)
PS C:\> ls $HOME\.config\totp-cli


    Directory: C:\Users\efert\.config\totp-cli


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          5/1/2021  11:30 AM             88 credentials


PS C:\>
```


Note: I don't know if the `update` is working or not. Most likely not because I changed the GitHub action for it.

**Comment by yitsushi** [comment]
The `update` command is working on linux and darwin, but not for windows because the new GitHub action uploads it as a zip not as a `tar.gz`. Filed #33

**Comment by sharunkumar** [comment]
> @sharunkumar: Can you check if it's working for you (v1.1.13)?
> 
> ```
> PS C:\> .\totp-cli.exe list
> Password: ***
> test (Number of accounts: 1)
> PS C:\> ls $HOME\.config\totp-cli
> 
> 
>     Directory: C:\Users\efert\.config\totp-cli
> 
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a----          5/1/2021  11:30 AM             88 credentials
> 
> 
> PS C:\>
> ```
> 
> Note: I don't know if the `update` is working or not. Most likely not because I changed the GitHub action for it.

Which one? the PS command or update?

the `ls` command works

however, this is what I am getting from `update`

```
PS C:\Users\Sharun> totp update
Check...
Your totp-cli is up-to-date. \o/
```

**Comment by yitsushi** [comment]
Just that the tool is working. If the ls command is working than it's working.
