### ISSUE TITLE
Ephemeral tokens 

### ISSUE THREAD

**Issue by ciaranmcnulty** [yitsushi/totp-cli#35]
I keep my 2fa tokens in 1password but would like to sign things at the CLI

It would be convenient for `generate` to optionally take the TOTP key on stdin, and ideally not require a password in those cases

**Comment by yitsushi** [comment]
So if I understand, a command that reads stdin and generates an otp for that without storing the value, just generate?

**Comment by yitsushi** [comment]
@ciaranmcnulty : Feel free to reopen the issue, if it's not what you requested.

**Comment by yitsushi** [comment]
Boom. I realized, the functionality was already there from Environment Variable. So I updated that command to read `stdin` if the `TOTP_TOKEN` environment variable is not defined.

Changes are available with [v1.1.17](https://github.com/yitsushi/totp-cli/releases/tag/v1.1.17)

**Comment by ciaranmcnulty** [comment]
That's great, thank you! Exactly what I wanted.
