### ISSUE TITLE
use better hashing than sha1

### ISSUE THREAD

**Issue by yitsushi** [yitsushi/totp-cli#41]
In general, better security. I don't even know why the Password is stored in the object itself. It's encrypted. The file is decrypted with the password and after that we don't need the password anymore.

**Comment by nuxi** [comment]
I've never programmed in go before, but I was looking for an excuse to tinker with it and gave this a try.

I don't think its ready for a real PR yet, but I have a branch that uses scrypt instead of sha1.

https://github.com/nuxi/totp-cli/commits/improve-kdf
