### ISSUE TITLE
Ability to batch import tokens

### ISSUE THREAD

**Issue by yaaminu** [yitsushi/totp-cli#48]
First of all, thanks for creating this project, looks really cool.

I have a google authenticator app installed on my phone and would like to use the same private key for this too. How do I do that?

**Comment by yitsushi** [comment]
I don't use Google Authenticator and I don't know if you can export or how to do that.

Importing it, that's a good question. As I know you can't do it yet. With a lot of keys, it would be painful to add one by one.

**Comment by yitsushi** [comment]
Note: Renamed the this issue to be an actionable one
