### ISSUE TITLE
Where is the existing credentials file stored?

### ISSUE THREAD

**Issue by ds-developers** [yitsushi/totp-cli#70]
I've successfully assigned a password and created a working OTP entry in the file, now I want to put that file onto shared storage for others to use.  Where is the file stored originally if I never set `TOTP_CLI_CREDENTIAL_FILE`?  

Documentation doesn't make it clear, and I can't seem to find any other file used.

**Comment by ds-developers** [comment]
It was found in `~/.config/totp-cli/credentials` -  maybe document that as well?

**Comment by yitsushi** [comment]
@ds-developers : Done, it's documented in the Readme file now.

**Comment by connell-theaa** [comment]
Thanks!
