### ISSUE TITLE
totp-cli update thinks it has succeeded when it hasn't

### ISSUE THREAD

**Issue by peterhoeg** [yitsushi/totp-cli#74]
In my case it's not expected to work (even if I used `sudo`, the binary comes from a place mounted read-only), but `totp-cli` still thinks it got updated:

```sh
$ totp-cli update                                  
Check...
Target: totp-cli-v1.3.1-linux-amd64.tar.gz
 -> Download...
 -> Extract...
Error: download error: open /nix/store/j1n6nzhdxd7xbsgpqznq3k8f2v860kv8-totp-cli-1.3.1/bin/totp-cli805377435: read-only file system
Now you have a fresh new totp-cli \o/
```

**Comment by yitsushi** [comment]
:rofl: that's a funny one. It handles the error, but continues as nothing happened (https://github.com/yitsushi/totp-cli/blob/main/internal/cmd/update.go#L60-L63).
