### ISSUE TITLE
Allow to specify password via env variable

### ISSUE THREAD

**Issue by igorlidin** [yitsushi/totp-cli#76]
It would be great (and rather simple) to add a feature to pass a password via environment variable, to allow for unattended usage from scripts, etc.

**Comment by yitsushi** [comment]
@igorlidin: Does my provided solution work for you? Can we close this one?

**Comment by igorlidin** [comment]
It works, but not common for tools like this. Imagine some another prompt besides password will be implemented in the future, and this trick will stop working.

**Comment by yitsushi** [comment]
`TOTP_PASS` is available with [v1.5.0](https://github.com/yitsushi/totp-cli/releases/tag/v1.5.0).
