### ISSUE TITLE
bash completion warning

### ISSUE THREAD

**Issue by dguest** [yitsushi/totp-cli#93]
I installed this with homebrew, and for some reason when my terminal starts up I was seeing

```
-bash: unset: `totp-cli': not a valid identifier
```

I managed to get rid of it by editing deleting [the unset line in the autocomplete](https://github.com/yitsushi/totp-cli/blob/main/autocomplete/bash_autocomplete#L35). Not sure if that was there for a good reason though. Should it be removed?

**Comment by yitsushi** [comment]
That files is coming from urfave: https://github.com/urfave/cli/blob/main/autocomplete/bash_autocomplete

I think that's correct, that line is a mistake at the end as we do not set a variable for that, just using `totp-cli` directly. My best guess I just did a quick `:% s/PROG/totp-cli/g` and as I don't use back, I didn't check it.
