### ISSUE TITLE
totp-cli Version 1.8.2 -- Binary Reports Wrong Version Number

### ISSUE THREAD

**Issue by RobK88** [yitsushi/totp-cli#98]
I downloaded the `totp-cli-v1.8.2-darwin-amd64.tar.gz` binary package and unzipped it.

But the binary reports version 1.8.0 not 1.8.2.  See below:

```
grinch$ ./totp-cli --version
totp-cli version v1.8.0
```

**Comment by RobK88** [comment]
P.S.  FYI -- I have updated the `totp-cli` port in MacPorts to version 1.8.2. 
See 
https://trac.macports.org/ticket/68676

I will submit a Pull Request to MacPorts shortly.

**Comment by yitsushi** [comment]
Pushed v1.8.3 with bumped version in `internal/info` too. Thank you

**Comment by yitsushi** [comment]
Closing this as the new version has proper version information and I have zero connection with macports (and I don't have any plans to do that as I don't even have a mac anymore)

**Comment by RobK88** [comment]
@yitsushi -- Many thanks.  Do not worry about MacPorts.  Lately, I have been maintaining the port.  And I will continue to do so.

FYI -- The `totp-cli` port in MacPorts builds and installs just fine on Macs running High Sierra and later.  MacPorts can successfully build either the x86_64 or ARM binaries (needed for the latest Macs using Apple silicon CPUs).  

See https://ports.macports.org/port/totp-cli/details/

P.S.  I am also working with the MacPorts developers to see if I can get `totp-cli` to build on older Macs (running Sierra and earlier) using the MacPorts `legacy-support` library and the older version of `go`.  (Unfortunately, the latest version of the `go` compiler only builds and runs on High Sierra and later).

Many thanks for developing `totp-cli`!
